export const VALID_MAJORS = [
    "Applied Mathematics",
    "Applied Sciences",
    "Architecture",
    "Biological Engineering",
    "Biomedical Engineering",
    "Business Management",
    "Civil Engineering",
    "Computer Engineering",
    "Computer Information Systems",
    "Computer Networking",
    "Computer Science",
    "Computer Science + Society",
    "Construction Management",
    "Cybersecurity",
    "Data Science",
    "Electrical Engineering",
    "Electromechanical Engineering",
    "Engineering",
    "Industrial Design",
    "Information Technology",
    "Interior Design",
    "Mechanical Engineering"
];