export const projects = [
    {
        key: 1, 
        bookmarked: false,
        liked: false,
        disliked: false,
        title: `Card 1`,
        text: 'This is Card 1\'s description',
    },
    {
        key: 2, 
        bookmarked: false,
        liked: false,
        disliked: false,
        title: `Card 2`,
        text: 'This is Card 2\'s description',
    },
    {
        key: 3, 
        bookmarked: false,
        liked: false,
        disliked: false,
        title: `Card 3`,
        text: 'This is Card 3\'s description',
    },
    {
        key: 4, 
        bookmarked: false,
        liked: false,
        disliked: false,
        title: `Card 4`,
        text: 'This is Card 4\'s description',
    },
    {
        key: 5, 
        bookmarked: false,
        liked: false,
        disliked: false,
        title: `Card 5`,
        text: 'This is Card 5\'s description',
    },
    {
        key: 6, 
        bookmarked: false,
        liked: false,
        disliked: false,
        title: `Card 6`,
        text: 'This is Card 6\'s description',
    },
    {
        key: 7, 
        bookmarked: false,
        liked: false,
        disliked: false,
        title: `Card 7`,
        text: 'This is Card 7\'s description',
    },
    {
        key: 8, 
        bookmarked: false,
        liked: false,
        disliked: false,
        title: `Card 8`,
        text: 'This is Card 8\'s description',
    },
    {
        key: 9, 
        bookmarked: false,
        liked: false,
        disliked: false,
        title: `Card 9`,
        text: 'This is Card 9\'s description',
    },
];
