/*
    This file is used to export verification or list populating data and store it organized in one file.
 */

export const NAME_REGEX = /^[A-Z][a-zA-Z- ]+$/;
export const EMAIL_REGEX = /[a-z0-9]@wit.edu/;
export const PWD_REGEX = /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%]).{8,24}$/;
export const PHONE_NUMBER_REGEX = /[0-9]+.{9}/;

export const DISCORD_REGEX = /.+[#d].{4}/;

export const VALID_MINORS = [
    "(Optional) Select minor...",
    "Aerospace Engineering",
    "American Studies",
    "Applied Math",
    "Architectural Studies",
    "Biology",
    "Business Analytics",
    "Chemistry",
    "Civil Engineering",
    "Computer Networking",
    "Computer Science",
    "Construction Management",
    "Cybersecurity Management",
    "Data Science",
    "Electrical Engineering",
    "Environmental Engineering",
    "Financial Mathematics",
    "Internet of Things",
    "Manufacturing",
    "Media, Culture, and Communication Studies",
    "Performing Arts",
    "Physics",
    "Science, Technology, and Society",
    "Sustainability"
];

export const TAGS = [
    "(Optional) Select tag...",
    "Technology",
    "Health",
    "Environment",
    "Education",
    "Government",
    "Finance",
    "Communications",
];

export const SKILLS = {
    "Select general skill...": {
        "Select skills focus...": ["Select specific skill..."],
    },
    "Computing and Data Science": {
        "Select skills focus...": ["Select specific skill..."],
        "Applied Mathematics": [
            "Select specific skill...",
            "Calculus",
            "Numerical Analysis",
            "Advanced Statistics",
            "Discrete Mathematics",
            "Differential Equations",
        ],
        "Computer Networking": [
            "Select specific skill...",
            "Routing and Switching",
            "Network Administration",
            "System Administration",
            "Web Development",
            "Project Management",
            "Network Security",
            "Wireless Networks"
        ],
        "Computer Science": [
            "Select specific skill...",
            "Software Engineering",
            "Mobile Development",
            "Web Development",
            "Backend Development",
            "Databases",
            "Network Programming",
            "Algorithms",
            "Data Structures",
        ],
        "Cybersecurity": [
            "Select specific skill...",
            "Offensive Security",
            "Computer Security",
            "Incident Response",
            "System Administration",
            "Network Security",
            "Network Administration",
            "Cryptography",
            "Scripting",
            "Forensics"
        ],
        "Data Science": [
            "Select specific skill...",
            "Programming",
            "Probability & Stats",
            "Data Mining",
            "Databases",
            "Machine Learning",
            "Data Visualization"
        ],
        "Information Technology": [
            "Select specific skill...",
            "Programming",
            "System Analysis & Design",
            "Security Principles",
            "Statistics & Applications",
            "Infrastructure Design",
            "Wireless Networks",
            "IT Software Development & Management",
            "Web Development",
            "Project Management"
        ],
    },
    "Science & Humanities": {
        "Select skills focus...": ["Select specific skill..."],
        "Applied Sciences": [
            "Select specific skill...",
            "Biology",
            "Biotech",
            "Medical",
            "Molecular Biology",
            "Physics," +
            "Chemistry",
            "Optics"
        ],
        "Computer Science & Society": [
            "Select specific skill...",
            "Social Research",
            "Data Visualization",
            "Data Management",
            "Human-Technology Interaction",
            "Ethics",
            "Urban Studies"
        ],
    },
    "Architecture & Design": {
        "Select skills focus...": ["Select specific skill...",],
        "Architecture": [
            "Select specific skill...",
            "Architectural Representation",
            "Architectural Media",
            "Building Matters",
            "Energy & Resources",
            "Pro-Practice",
            "Structures",
            "Passive & Active Systems",
            "Concentration Studies",
            "Urbanism Concentration",
            "Engineering Technologies Concentration," +
            "Adaptive Interventions Concentration",
            "Geospatial Modeling",
            "Design Strategies for Low-Carbon Buildings",
            "Holistic Sustainable Design Integration",
            "Animated Architectural Manufacturing",
            "Potentials of Additive Manufacturing",
            "Architects. Directors, Scenographers",
            "Collage",
            "Green & Resilient Design",
            "Color Relationships",
            "Modernism Beyond the West",
            "Material Intelligence",
            "Issues in Professional Practice," +
            "Context Analysis-Berlin",
            "Space & Media",
            "City of the Future",
            "Building Community",
            "Project Planning",
            "Framing Chinese Architecture",
            "Mutli(ply)",
            "Fundamentals of Design Finance",
            "Explorations in Making"
        ],
        "Industrial Design": [
            "Select specific skill...",
            "Visualization/Drawing",
            "Visual Communication",
            "Visualization: Advanced Perspective",
            "Visualization: Presentation & Illustration",
            "Plane & Solid Geometry",
            "Visualization: Draw & Think",
            "CAD",
            "Surface Modeling",
            "3D Realization",
            "Solid Modeling",
            "Human Factors in Design",
            "Information Architecture",
            "Manufacturing in Design",
            "Business in Design",
        ],
        "Interior Design": [
            "Select specific skill...",
            "Visualization/Drawing",
            "Design Magic",
            "Color & Composition",
            "History of Interiors",
            "Drawing",
            "Materials",
            "Building Systems",
            "Presentation Techniques",
            "Construction Documents",
            "Behavioral Aspects of Design",
            "Building Systems & Interior Specification",
            "Lighting",
            "Building Regulations",
            "Professional Practice"
        ],
    },
    "Engineering": {
        "Select skills focus...": ["Select specific skill..."],
        "Biological Engineering": [
            "Select specific skill...",
            "Applied Engineering Analysis",
            "Cell & Molecular Biology",
            "Advanced Molecular Biology",
            "Biostatistics",
            "Biological Instrumentation & Measurement",
            "General Chemistry",
            "Organic Chemistry",
            "Biomaterials & Tissue Engineering",
            "Unit Operations & Process Control",
            "Bio-transport Phenomena",
            "Synthetic Biology",
        ],
        "Biomedical Engineering": [
            "Select specific skill...",
            "Cell & Molecular Biology",
            "Applied Engineering Analysis",
            "Engineering Physics",
            "Anatomy & Physiology",
            "Electrical Circuit Analysis & Design",
            "Biomedical Electronics & Instrumentation",
            "Integrated Electronics",
            "Organic & Biochemistry",
            "Engineering Mechanics",
            "Biomaterials & Tissue Engineering",
            "Biostatistics",
        ],
        "Civil Engineering": [
            "Select specific skill...",
            "Applied Engineering Analysis",
            "Engineering Physics",
            "Statistics & Mechanics Materials",
            "Geomatics",
            "CAD",
            "Civil Engineering Materials",
            "Engineering Economy",
            "Fluid Mechanics",
            "Environmental Engineering",
            "Structural Analysis",
            "Soil Mechanics",
            "Highway Engineering",
            "Hydraulic Engineering",
            "Probability & Statistics for Engineers"
        ],
        "Computer Engineering": [
            "Select specific skill...",
            "Applied Engineering Analysis",
            "Network Theory",
            "Digital Logic",
            "Microcontrollers Using C Programs",
            "Object Oriented Programming",
            "Analog Circuit Design",
            "Computer Architecture",
            "Advanced Digital Circuit Design",
            "Applied Programming Concepts",
            "Computer Networks",
            "Signals and Systems",
            "Operating Systems",
            "Engineering Economy",
            "Probability & Statistics for Engineers"
        ],
        "Electrical Engineering": [
            "Select specific skill...",
            "Applied Engineering Analysis",
            "Network Theory",
            "Digital Logic",
            "Microcontrollers Using C Programs",
            "Analog Circuit Design",
            "Signals and Systems",
            "Engineering Mechanics",
            "Object Oriented Programming",
            "Solid State Devices",
            "Motors and Controls",
            "Feedback and Control",
            "Engineering Economy",
            "Probability & Statistics for Engineers",
            "Engineering Communication Systems",
            "Electromagnetic Field Theory"
        ],
        "Electromechanical Engineering": [
            "Select specific skill...",
            "Applied Engineering Analysis",
            "Digital Logic",
            "Circuit Analysis",
            "Engineering Thermodynamics",
            "Applied Mechanics",
            "Microcontrollers Using C Programs",
            "Analog Circuit Design",
            "Engineering Fluid Mechanics",
            "Probability & Statistics for Engineers",
            "Signals and Systems",
            "Materials Science",
            "Engineering Heat Transfer",
            "Feedback and Control",
            "Engineering Dynamics",
            "Electromechanical Systems"
        ],
        "Mechanical Engineering": [
            "Select specific skill...",
            "Applied Engineering Analysis",
            "Engineering Statics",
            "Engineering Graphics",
            "Circuit Theory and Application",
            "Engineering Thermodynamics",
            "Mechanics of Materials," +
            "Design of Machine Elements",
            "Engineering Fluid Mechanics",
            "Materials Science",
            "Simulation Based Design",
            "Macroeconomics",
            "Microeconomics",
            "Project Management Concentration",
            "Entrepreneurship Concentration",
            "Cybersecurity Management Concentration"
        ],
    },
    "Management": {
        "Select skills focus...": ["Select specific skill..."],
        "Business Management": [
            "Select specific skill...",
            "Decision Analysis",
            "Integrative Financial Accounting",
            "Management Information Systems",
            "Management Communications",
            "Research Methods",
            "System Analysis & Design",
            "Principles of Marketing",
            "Managerial Accounting",
            "Managing & Leading Organizations",
            "Business Law",
            "Financial Management",
            "Human Resources & Labor Management",
            "Operations Management",
            "Strategic Management",
            "Business Negotiation Principles",
            "International Business"
        ],
        "Computer Information Systems": [
            "Select specific skill...",
            "Computer Business Applications",
            "Management Information Systems",
            "Decision Analysis for Business",
            "Statistics & Applications",
            "Management Communications",
            "Databases",
            "System Analysis & Design",
            "Applied Project Management",
            "Security Principles",
            "Integrative Financial Accounting",
            "Technology Acquisition",
            "Principles of Marketing",
            "Business Law",
            "Managing & Leading Organizations",
            "Financial Management",
            "E-Commerce"
        ],
        "Construction Management": [
            "Select specific skill...",
            "Building Construction",
            "Construction Graphics",
            "Heavy Construction Equipment",
            "Construction Surveying",
            "Statics & Strength of Materials",
            "Estimating",
            "Financial Accounting",
            "Building Systems",
            "Wood & Steel Analysis & Design",
            "Statistics & Applications",
            "Materials Testing & Quality Controls",
            "Construction Project Management",
            "Construction Project Scheduling",
            "Managing & Leading Organizations",
            "Advanced Estimating & Bid Analysis",
            "Concrete Analysis & Design",
            "Construction Project Control",
            "Construction Business & Finance",
            "Construction Safety & Risk Management",
            "Power & Leadership in Organizations",
            "Business, Construction Law & Government Regulations",
            "Labor Relations"
        ],
    },
};